### ISSUE TITLE
status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM

### ISSUE THREAD

**Issue by felipheggaliza** [CMU-Perceptual-Computing-Lab/openpose#10]
Hi guys, I tried to run some demos, but I got the error shown below:

feliphe@synthetic-nb1:~/openpose$ sudo ./build/examples/openpose/rtpose.binStarting pose estimation demo.
Starting thread(s)
F0505 15:14:03.078338 23156 cudnn.hpp:100] Check failed: status == CUDNN_STATUS_SUCCESS (3 vs. 0)  CUDNN_STATUS_BAD_PARAM
*** Check failure stack trace: ***
    @     0x7f887fe195ad  google::LogMessage::Fail()
    @     0x7f887fe1b413  google::LogMessage::SendToLog()
    @     0x7f887fe1913b  google::LogMessage::Flush()
    @     0x7f887fe1bdfe  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f887e082995  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f887df43b5d  caffe::Net<>::Init()
    @     0x7f887df46bca  caffe::Net<>::Net()
    @     0x7f888016f45e  op::NetCaffe::initializationOnThread()
    @     0x7f88800ab59e  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f88800e9571  op::SubThread<>::initializationOnThread()
    @     0x7f88800e9b60  op::Thread<>::initializationOnThread()
    @     0x7f88800ee4dd  op::Thread<>::threadFunction()
    @     0x7f887f91bc20  (unknown)
    @     0x7f887f4326ca  start_thread
    @     0x7f887f16c0af  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by RainBoltz** [comment]
since this error message often appears:
1. if gpu compute capability is under 3.0, maybe try not to compile with cudnn (comment USE_CUDNN in Makefile.config, both openpose and caffe)
2. maybe the GPU is out of use, just close the processes that are using GPU

**Comment by gineshidalgo99** [comment]
For @RainBoltz comment, thank you for point 2! About point 1, OpenPose must be compiled with cuDNN support (by default it is enabled in both OpenPose and the Caffe we provide in 3rdparty/caffe). If you disable it, Caffe would ask for more than 12 GB of GPU memory for our model.

@felipheggaliza  Which Ubuntu, CUDA and cuDNN versions are you using? The script only works for CUDA 8, otherwise you must use the manual steps to install it: [doc/installation.md](../blob/master/doc/installation.md). Thanks!

**Comment by vermicelli** [comment]
I got this error too. I'm using cuda8.0 and cudnn5.1.10.

**Comment by vermicelli** [comment]
Problem solved by using the BVLC version of caffe library.

**Comment by gineshidalgo99** [comment]
@vermicelli  Thank you for your feed-back. But we are basically using almost the same version, just with cuDNN and c++11 flags enabled (otherwise your computer will run out of memory). Did you disable cuDNN or how did you do it? Thanks!

**Comment by felipheggaliza** [comment]
Hi @gineshidalgo99! I am also using cuda 8.0 and cudnn 5.1.10.

**Comment by malchun** [comment]
Got same trouble. Had to reinstall manually cudnn6 (not from deb this time) and remake project. Worked for me.
Cuda 8.0, cuDNN 6.0.21, Ubuntu 16.04

**Comment by gineshidalgo99** [comment]
Thank you @malchun !

@felipheggaliza , does malchun solution works for you? Remember you need to perform a clean install after recompiling cuDNN (steps in doc/installation.md).

**Comment by vermicelli** [comment]
@gineshidalgo99 I built the BLVC caffe with cuDNN enabled but without c++11 flag, using the source code I cloned 2 weeks ago.

**Comment by gineshidalgo99** [comment]
@vermicelli Thank you for your feed-back!

I will close this thread then.

**Comment by hossam-96** [comment]
I have the same error.
so what should I do? remove cudnn 5.1 and install cudnn 6? or build it with the BLVC caffe ?

**Comment by hossam-96** [comment]
> I have the same error.
so what should I do? remove cudnn 5.1 and install cudnn 6? or build it with the BLVC caffe ?

I solved it by installing cudnn v6 and remake from begining

**Comment by hscspring** [comment]
i got the same issue,  
i think the `./ubuntu/*.sh` in the github might not work now.  

for example:  
[openpose/installation.md at master · CMU-Perceptual-Computing-Lab/openpose](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#prerequisites), `sudo ubuntu/install_cuda.sh` this command will install cuda9 instead of cuda8.  
i don't sure what exactly version i should install, maybe docker is good enough...  

the same issues are:  
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/62  
https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/153 . 

the problems they have faced were almost the same, but their solutions seemed different from each other....

**Comment by gineshidalgo99** [comment]
@hscspring The command do install cuda8 (unless you are using some old version of OpenPose?). We recommend CUDA 8 (for Caffe compatibility). Cuda 9 is also possible, but might require you some extra step with Caffe

**Comment by bragilee** [comment]
@gineshidalgo99 Hi, I am facing the same problem with cud 8.0+cudnn 7. Is the problem caused by cudnn version? Thank you. :)

**Comment by gineshidalgo99** [comment]
Unfortunately, the problem is coming from CUDA/cuDNN, so I can't not help much debugging it. But no, it should not be because of the version, rather a cuda/cudnn installation issue.

**Comment by bragilee** [comment]
@gineshidalgo99  Thank you for your clarification. I will find out possible ways to solve it. Thanks. :)

**Comment by kccheung** [comment]
I also encounter similar problem (with CUDA 9.0 and cuDNN 5.1.0), but the problem seems gone after I installed the latest version of cuDNN 7.2.1.38. You could check the cuDNN version you installed by reading the log message during make or using `cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2`.

**Comment by Harsharma2308** [comment]
Installing cudnn v6 instead of v5 didn't work for me. I get similar error on running from both of them.
