### ISSUE TITLE
Jetson TX1 - pooling_layer.cu:212] Check failed: error == cudaSuccess (40 vs. 0) 

### ISSUE THREAD

**Issue by aashishsoni05** [CMU-Perceptual-Computing-Lab/openpose#1045]
Hello
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
F0123 10:55:27.467897 13141 pooling_layer.cu:212] Check failed: error == cudaSuccess (48 vs. 0) no kernel image is available for execution on the device
*** Check failure stack trace: ***
@ 0x7f92b39718 google::LogMessage::Fail()
@ 0x7f92b3b614 google::LogMessage::SendToLog()
@ 0x7f92b39290 google::LogMessage::Flush()
@ 0x7f92b3beb4 google::LogMessageFatal::~LogMessageFatal()
@ 0x7f92f40bc8 caffe::PoolingLayer<>::Forward_gpu()
@ 0x7f92d66058 caffe::Net<>::ForwardFromTo()
@ 0x7f93e68a2c op::NetCaffe::forwardPass()
@ 0x7f93f9897c op::PoseExtractorCaffe::forwardPass()
@ 0x7f93f8e178 op::PoseExtractor::forwardPass()
@ 0x7f93f9cc18 op::WPoseExtractor<>::work()
@ 0x7f93e96bac op::Worker<>::checkAndWork()
@ 0x7f93e9b528 op::SubThread<>::workTWorkers()
@ 0x7f93ea57cc op::SubThreadQueueInOut<>::work()
@ 0x7f93ea1308 op::Thread<>::threadFunction()
@ 0x7f9394f280 (unknown)
@ 0x7f91f77fc4 start_thread
Aborted
facing the above error with TX1. tried the changes mentioned in #58  Please guide here.

**Comment by aashishsoni05** [comment]
Hello, 

any update on this, please.

**Comment by aashishsoni05** [comment]
Hello,
I am facing an issue of zero people detected. tried everything mentioned in FAQ document. 
I had to use the flags --num_gpu 0 --camera 1, only then the above error is being fixed but still, there is no detection.

**Comment by gineshidalgo99** [comment]
Num_gpu 0 is literally telling OpenPose to run without GPU processing, leading to no person detection (so that output is the expected one). I believe this is an architecture missmatch when cuda was compiled. Make sure you select the right cuda architecture when compiling OpenPose.

**Comment by aashishsoni05** [comment]
thank, it worked after changing the respective Cuda arch.
