### ISSUE TITLE
cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED

### ISSUE THREAD

**Issue by xufunly** [CMU-Perceptual-Computing-Lab/openpose#1249]
### Posting rules
1. 
python demo: examples\tutorial_api_python\01_body_from_image.py 
code line:  opWrapper.emplaceAndPop([datum])
get err: 
F0608 08:30:11.604262 10688 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***

2. My System Configuration 
  CPU Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Win10
  NVIDIA GeForce RTX 2060, Driver Version 430.86
  CUDA v10.0
  cudnn 7.5.0

  python code, get error, F0608 08:30:11.604262 10688 cudnn_conv_layer.cu:28] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0)  CUDNN_STATUS_EXECUTION_FAILED
*** Check failure stack trace: ***
   can anyone help me, thanks!

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### Type of Issue
You might select multiple topics, delete the rest:
- Compilation/installation error
- Execution error
- Help wanted
- Question
- Enhancement / offering possible extensions / pull request / etc
- Other (type your own type)

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code? Or specific commit (e.g., d52878f)? Or specific version from `Release` section (e.g., 1.2.0)?

3. **General configuration**:
    - **Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); CMake, ... (Windows); ...?
    - **Operating system** (`lsb_release -a` in Ubuntu):
    - **Operating system version** (e.g., Ubuntu 16, Windows 10, ...):
    - **Release or Debug mode**? (by default: release):
    - Compiler (`gcc --version` in Ubuntu or VS version in Windows): 5.4.0, ... (Ubuntu); VS2015 Enterprise Update 3, VS2017 community, ... (Windows); ...?

4. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

5. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

6. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    - **cuDNN version**:
    - **GPU model** (`nvidia-smi` in Ubuntu):

7. If **CPU-only mode** issue:
    - **CPU brand & model**:
    - Total **RAM memory** available:

8. If **Python** API:
    - **Python version**: 2.7, 3.7, ...?
    - **Numpy version** (`python -c "import numpy; print numpy.version.version"` in Ubuntu):

9. If **Windows** system:
    - Portable demo or compiled library?

10. If **speed performance** issue:
    - Report OpenPose timing speed based on [this link](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/speed_up_openpose.md#profiling-speed).

**Comment by fabian57fabian** [comment]
I'm having the same issue.
**Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED**
Similar to the **Check failed: error == cudaSuccess (2 vs. 0) out of memory**, it seemed like a low GPU memory but it can be a problem with CUDA and cuDNN: you should download a version of cuDNN that supports your CUDA version

**Comment by fabian57fabian** [comment]
I solved this buying a brand new GTX 1660ti Armor Oc 6G.
Upragrated from 2 Gb to 6 Gb, now it works perfectly.
I also used CUDA 10.0 and cuDNN 7.5.

**Comment by imistyrain** [comment]
The architure of 20x0 is Turing, the compute ability is compute_75, you should change some code of caffe and rebuild it as [Windows+RTX2080+Caffe+Yolo配置](https://blog.csdn.net/OPTHREE/article/details/84866819)

**Comment by CrazyReason** [comment]
I also encountered the same problem
OpenPoseDemo.exe  --video  xxx.avi
get err:
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0707 16:24:19.065626 11580 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***

My System Configuration
CPU: amd 2700X 
GPU:RTX2080  
CUDA 10.0 and cuDNN 7.5.

can anyone help me, thanks!

**Comment by CrazyReason** [comment]
Updating the latest version can solve this problem

**Comment by gineshidalgo99** [comment]
Seems that the error no longer happens in the latest version.

**Comment by xufunly** [comment]
Thanks @ALL，the latest version can solve this problem

**Comment by hooman67** [comment]
@gineshidalgo99   updating the latest version of what?

**Comment by ycyoon** [comment]
I still have same problem although I'm using the latest openpose version

**Comment by Sunny478** [comment]
> I encounted this problem with the latest openpose version.
> I solved this problem by building without CUDNN
How did you build without CUDNN in ubuntu ?

**Comment by g782373711** [comment]
> I encounted this problem with the latest openpose version.
> I solved this problem by building without CUDNN

me too，I try to update CUDNN ,but it doesn't work.
finally, I comment CUDNN in Makefile.Config

**Comment by learninginvision** [comment]
> > I encounted this problem with the latest openpose version.
> > I solved this problem by building without CUDNN
> 
> me too，I try to update CUDNN ,but it doesn't work.
> finally, I comment CUDNN in Makefile.Config, but this solution can‘t give full play to CUDNN abilities

I have the same problem, when I comment USE_CUDNN := 1 in Makefile.Config, it can successfully pass runtest, but when I uncomment this command, and make runtest, I will get this error. Do you find any answer? Any answer is appreciated!
![image](https://user-images.githubusercontent.com/65346642/124074364-f9afaa00-da75-11eb-9a3e-c5fb08dd839e.png)
