### ISSUE TITLE
05_keypoints_from_images_multi_gpu.py

### ISSUE THREAD

**Issue by akhalili** [CMU-Perceptual-Computing-Lab/openpose#1739]
I get "Segmentation fault (core dumped)" despite other examples (e.g 01_body_from_image.py) works.

Here are my specs:
Ubuntu 18.04
GPU Pascal Titan XP
used cuda and cudnn:

CUDA detected: 10.2
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Added CUDA NVCC flags for: sm_61
-- Found cuDNN: ver. 7.6.5 found (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libcudnn.so)
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)

any solution for the problem?

thanks

**Comment by frankier** [comment]
I think this might be a result of my patch. The ownership of objects between Python/C++ and the vector<shared_ptr<Datum>> between different threads within C++ is a bit tricky. I probably did not manage to correctly handle this case.

I don't have easy (local) access to a machine with two GPUs at the moment. I might have to set it up so I can test this configuration somehow, but for the time being, can you please compile with debugging information enabled (`-DCMAKE_BUILD_TYPE=Debug`) **and** debug logging turned on (see https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/d6174a2ce16042640fcb7e1b4567858298f1c6cc/doc/library_how_to_develop.md ) and run through gdb and paste the stack trace / any output.

Here are a couple of workarounds you can use for the time being:
 * Use OpenPose v1.6.0
 * Use the master branch with AsynchronousOut mode. You can start from https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/examples/tutorial_api_python/12_asynchronous_custom_output.py . If you use this as-is, it should use all available GPUs I think (since num_gpus defaults to -1). This is only possible if you are loading from a directory of images or a video file, but in these cases it should be faster.
   * In case the bug occurs in this case too, please let me know!

**Comment by akhalili** [comment]
Thanks I found the problem was because the cafe was built with another version of cuda
