### ISSUE TITLE
CUDNN error in Ubuntu 20.04

### ISSUE THREAD

**Issue by monacv** [CMU-Perceptual-Computing-Lab/openpose#1815]
I am getting the following error for `cmake-gui ..` command in `build` directory when I click on `configure` button:

Specifically, the following line doesn't take care of `Ubuntu 20.04` OS.
`if [[ $UBUNTU_VERSION == *"14."* ]] || [[ $UBUNTU_VERSION == *"15."* ]] || [[ $UBUNTU_VERSION == *"16."* ]]; thenn:`
```

GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 10.1
Added CUDA NVCC flags for: sm_75
cuDNN not found
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found Glog: /usr/include  
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Warning at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 3.13.0 doesn't match library version 3.6.1
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


cuDNN not found.
#!/bin/bash

echo "This script assumes Ubuntu 16 or 14 and Nvidia Graphics card up to 10XX. Otherwise, it will fail."

# Install cuDNN 5.1
if [[ $UBUNTU_VERSION == *"14."* ]] || [[ $UBUNTU_VERSION == *"15."* ]] || [[ $UBUNTU_VERSION == *"16."* ]]; then
	CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz"
	wget -c ${CUDNN_URL}
	sudo tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
	rm cudnn-8.0-linux-x64-v5.1.tgz && sudo ldconfig
else
	echo "cuDNN NOT INSTALLED! Ubuntu 16 or 14 not found. Install cuDNN manually from 'https://developer.nvidia.com/cudnn'."
fi

CMake Error at CMakeLists.txt:520 (message):
  Install cuDNN using the above commands.  or turn off cuDNN by setting
  USE_CUDNN to OFF.


Configuring incomplete, errors occurred!
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeError.log".
```

**Comment by gineshidalgo99** [comment]
You are probably not using the latest OpenPose? Which OpenPose version are you using? Only the latest (1.7.0 or newer) will work with Ubuntu 20.

**Comment by monajalal** [comment]
I did the git clone from this repo today so I'd say it is the latest version.

**Comment by monacv** [comment]
also @gineshidalgo99 is there a way to make it work with Protobuf 3.13.0? 

I even installed 3.6.1 but I don't know why it is not showing?
Here's the details
https://askubuntu.com/questions/1305387/getting-rid-of-protobuf-3-13-0-in-ubuntu-20-04-and-set-protobuf-3-6-1-as-default

**Comment by monacv** [comment]
@gineshidalgo99  when I do a git log this is what I get
```

$ git log
commit a255747af22116ad76004437456bb531dc5d0b23 (HEAD -> master, origin/master, origin/HEAD)
Author: Wlad Meixner <9556979+gosticks@users.noreply.github.com>
Date:   Mon Dec 21 22:01:10 2020 +0100

    Fix possible typo (#1802)
```

**Comment by monacv** [comment]
@gineshidalgo99  how can I make sure I have the latest version of openpose that will work with Ubuntu 20.04? Could you please share some commands? Thanks a bunch

**Comment by monacv** [comment]
Here's some logs:

```
[38130:4668 0:2001] 03:57:03 Wed Jan 06 [mona@goku:pts/6 +1] ~/research/code/openpose/build
$ cmake ..
-- GCC detected, adding compile flags
-- GCC detected, adding compile flags
-- Building with CUDA.
-- CUDA detected: 10.1
-- Added CUDA NVCC flags for: sm_75
-- cuDNN not found
-- Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
-- Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:469 (file):
  file STRINGS file "/usr/include/google/protobuf/stubs/common.h" cannot be
  read.
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:475 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:476 (math):
  math cannot parse the expression: " / 1000 % 1000": syntax error,
  unexpected exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:477 (math):
  math cannot parse the expression: " % 1000": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Warning at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 3.13.0 doesn't match library version
  ERROR.ERROR.ERROR
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "ERROR.ERROR.ERROR") 
-- cuDNN not found.
#!/bin/bash

echo "This script assumes Ubuntu 16 or 14 and Nvidia Graphics card up to 10XX. Otherwise, it will fail."

# Install cuDNN 5.1
if [[ $UBUNTU_VERSION == *"14."* ]] || [[ $UBUNTU_VERSION == *"15."* ]] || [[ $UBUNTU_VERSION == *"16."* ]]; then
	CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz"
	wget -c ${CUDNN_URL}
	sudo tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
	rm cudnn-8.0-linux-x64-v5.1.tgz && sudo ldconfig
else
	echo "cuDNN NOT INSTALLED! Ubuntu 16 or 14 not found. Install cuDNN manually from 'https://developer.nvidia.com/cudnn'."
fi
CMake Error at CMakeLists.txt:520 (message):
  Install cuDNN using the above commands.  or turn off cuDNN by setting
  USE_CUDNN to OFF.


-- Configuring incomplete, errors occurred!
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeError.log".
1782/31772MB
[38130:4668 0:2002] 03:57:07 Wed Jan 06 [mona@goku:pts/6 +1] ~/research/code/openpose/build
```
and then:

![Screenshot from 2021-01-06 15-58-52](https://user-images.githubusercontent.com/76495162/103819301-24c1bf80-5038-11eb-9aaa-4e3f02fa951e.png)


```
GCC detected, adding compile flags
GCC detected, adding compile flags
Building with CUDA.
CUDA detected: 10.1
Added CUDA NVCC flags for: sm_75
cuDNN not found
Found gflags  (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libgflags.so)
Found glog    (include: /usr/include, library: /usr/lib/x86_64-linux-gnu/libglog.so)
CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:469 (file):
  file STRINGS file "/usr/include/google/protobuf/stubs/common.h" cannot be
  read.
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:475 (math):
  math cannot parse the expression: " / 1000000": syntax error, unexpected
  exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:476 (math):
  math cannot parse the expression: " / 1000 % 1000": syntax error,
  unexpected exp_DIVIDE (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Error at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:477 (math):
  math cannot parse the expression: " % 1000": syntax error, unexpected
  exp_MOD (2).
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


CMake Warning at /usr/share/cmake-3.16/Modules/FindProtobuf.cmake:499 (message):
  Protobuf compiler version 3.13.0 doesn't match library version
  ERROR.ERROR.ERROR
Call Stack (most recent call first):
  CMakeLists.txt:429 (find_package)


cuDNN not found.
#!/bin/bash

echo "This script assumes Ubuntu 16 or 14 and Nvidia Graphics card up to 10XX. Otherwise, it will fail."

# Install cuDNN 5.1
if [[ $UBUNTU_VERSION == *"14."* ]] || [[ $UBUNTU_VERSION == *"15."* ]] || [[ $UBUNTU_VERSION == *"16."* ]]; then
	CUDNN_URL="http://developer.download.nvidia.com/compute/redist/cudnn/v5.1/cudnn-8.0-linux-x64-v5.1.tgz"
	wget -c ${CUDNN_URL}
	sudo tar -xzf cudnn-8.0-linux-x64-v5.1.tgz -C /usr/local
	rm cudnn-8.0-linux-x64-v5.1.tgz && sudo ldconfig
else
	echo "cuDNN NOT INSTALLED! Ubuntu 16 or 14 not found. Install cuDNN manually from 'https://developer.nvidia.com/cudnn'."
fi

CMake Error at CMakeLists.txt:520 (message):
  Install cuDNN using the above commands.  or turn off cuDNN by setting
  USE_CUDNN to OFF.


Configuring incomplete, errors occurred!
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeOutput.log".
See also "/home/mona/research/code/openpose/build/CMakeFiles/CMakeError.log".
```

**Comment by monacv** [comment]
This is the version listed in the CMakeList.txt file I have:
```

### VERSION INFO
set(OpenPose_VERSION_MAJOR 1)
set(OpenPose_VERSION_MINOR 7)
set(OpenPose_VERSION_PATCH 0)
set(OpenPose_VERSION ${OpenPose_VERSION_MAJOR}.${OpenPose_VERSION_MINOR}.${OpenPose_VERSION_PATCH})

```

**Comment by monacv** [comment]
Please let me know if there's a solution for this. For now, I have turned off the CUDNN flag in cmake-gui

**Comment by gineshidalgo99** [comment]
Make sure to follow the pre-requisites section and install cuDNN as instructed in those, thanks

**Comment by Net-Maker** [comment]
> Ubuntu 22.04, cuDNN 8.8.1, CUDA 11.7, master branch of this repo
> 
> ```
> cd openpose/
> mkdir build/
> cd build/
> cmake -DBUILD=PYTHON ON ..
> ```
> 
> yields the same exact error about requiring Ubuntu 14/16 and a 10** series card? .. Would like to build this with latest cuDNN, which is 100% installed (via the dpkg from Nvidia for x86_64).
> 
> Is there an updated CMakelists.txt or scripts/ directory in another branch or what do I need to do to build with cuDNN? Looks like master branch is out of date or I'm overlooking doing something for the build maybe?

Same error.Have you sloved it? @WyattAutomation

**Comment by Net-Maker** [comment]
> > Ubuntu 22.04, cuDNN 8.8.1, CUDA 11.7, master branch of this repo
> > ```
> > cd openpose/
> > mkdir build/
> > cd build/
> > cmake -DBUILD=PYTHON ON ..
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > yields the same exact error about requiring Ubuntu 14/16 and a 10** series card? .. Would like to build this with latest cuDNN, which is 100% installed (via the dpkg from Nvidia for x86_64).
> > Is there an updated CMakelists.txt or scripts/ directory in another branch or what do I need to do to build with cuDNN? Looks like master branch is out of date or I'm overlooking doing something for the build maybe?
> 
> Same error.Have you sloved it? @WyattAutomation

I solved the problem after some attempts.
I am using the .deb file to install cudnn.It would install the cudnn to /usr/local/cuda by default.
But cmake would detect your latest cuda version.So that's the problem.
I solved the problem by download the .tar.xz file,then extract it and following the command.
`cd <THE_PATH_YOU_EXTRACT_CUDNN>`
`cd include`
`mv ./* /usr/local/<THE_CUDA_DIRECTORY_YOUR_CMAKE_CHOOSE>/include`
`cd ../bin`
`mv ./* /usr/local/<THE_CUDA_DIRECTORY_YOUR_CMAKE_CHOOSE>/bin64>`
then it worked
