### ISSUE TITLE
TypeError: emplaceAndPop(): incompatible function arguments.

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [CMU-Perceptual-Computing-Lab/openpose#1903]
I have a error in executing using the following command.

`python3 run_video.py --path='/home/****/openpose/build/examples/tutorial_api_python/' --video='youtube_golf2.mp4'  --plt_graph=True`

Then, the following error message appeared.

```
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
/home/****/openpose/build/examples/tutorial_api_python/
/home/****/openpose/build/examples/tutorial_api_python/movies/youtube_golf2.mp4
APP_LOG, INFO:	OPEN: youtube_golf2.mp4
Traceback (most recent call last):
  File "run_video.py", line 250, in <module>
    cog_color=args.cog_color, start_frame=args.start_frame, debug=args.debug)
  File "run_video.py", line 117, in run_video
    opWrapper.emplaceAndPop([datum])
TypeError: emplaceAndPop(): incompatible function arguments. The following argument types are supported:
    1. (self: openpose.pyopenpose.WrapperPython, arg0: std::vector<std::shared_ptr<op::Datum>, std::allocator<std::shared_ptr<op::Datum> > >) -> bool

Invoked with: <openpose.pyopenpose.WrapperPython object at 0x7faa696d8fb8>, [<openpose.pyopenpose.Datum object at 0x7fa9f6e85a40>]

Did you forget to `#include <pybind11/stl.h>`? Or <pybind11/complex.h>,
<pybind11/functional.h>, <pybind11/chrono.h>, etc. Some automatic
conversions are optional and require extra headers to be included
when compiling your pybind11 module.
F0327 07:02:59.669406 17840 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
```

I don't know what the cause is and how to fix it.
Please tell me the solution if you know.

Environment is as follows:

Ubuntu18.04
Python3.6.9

Build commands are as follows:

```
cmake -DBUILD_PYTHON=true ..
make -j`nproc
```

**Comment by ravijo** [comment]
@Ishihara-Masabumi 

From the error message, I can see these two lines:
```
  File "run_video.py", line 117, in run_video
    opWrapper.emplaceAndPop([datum])
```

Assuming you are using OpenPose v1.7.0, you need to edit your file run_video.py as shown below:

**Before**
```
opWrapper.emplaceAndPop([datum])
```
**Now**
```
opWrapper.emplaceAndPop(op.VectorDatum([datum]))
```
Please feel free to look at [an example provided here](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/v1.7.0/examples/tutorial_api_python/01_body_from_image.py).

**Comment by ravijo** [comment]
@Ishihara-Masabumi 

Just for reference, I am writing this comment. The above [problem `TypeError: emplaceAndPop(): incompatible function arguments` was discussed here as well](https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1718).

**Comment by Ishihara-Masabumi** [comment]
Hi ravijo,

Thank you very much for fixing this error.
I tried to run the same command line after rewriting run_video.py as you suggested.
The error disappeared.

But, another error happened.

```
Starting OpenPose Python Wrapper...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
/home/****/openpose/build/examples/tutorial_api_python/
/home/****/openpose/build/examples/tutorial_api_python/movies/youtube_golf2.mp4
APP_LOG, INFO:	OPEN: youtube_golf2.mp4
F0401 14:44:27.152856 17275 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
```

The error above means out of GPU memory.
So I will try this on another machine.

Best Regards,
