### ISSUE TITLE
Error: Cuda check failed (209 vs. 0): no kernel image is available for execution on the device

### ISSUE THREAD

**Issue by shiva-kumarj** [CMU-Perceptual-Computing-Lab/openpose#1953]
### Issue Summary
I am trying to run the openpose example on Google colab. Since building the code takes a very long time. I decided to build it once with all the correct models and copied it to my google drive. Then I copied it back to the current session in a new notebook, and ran the demo application

I made sure that GPU was enabled in this notebook and I made sure that all the built files were copied correctly.

What should I do to resolve this ?

### Executed Command (if any)

`!cd ./openpose && ./build/examples/openpose/openpose.bin --logging_level 0 --maximize_positives --image_dir ./examples/media/ --maximize_positives --write_json ./output --display 0 --write_images ../body`

### OpenPose Output (if any)
[Error.txt](https://github.com/CMU-Perceptual-Computing-Lab/openpose/files/6527576/Error.txt)

### Errors (if any)
`Error occurred on a thread. OpenPose closed all its threads and then propagated the error to the main thread. Error description:
Cuda check failed (209 vs. 0): no kernel image is available for execution on the device`

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **Whole console output** (if errors appeared), paste the error to [PasteBin](https://pastebin.com/) and then paste the link here: LINK

2. **OpenPose version**: Latest GitHub code

6. If **GPU mode** issue:
    - **CUDA Version 11.0.228** 
    - **cuDNN version 7.6.5**: 
    - **GPU model** NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2    

8. If **Python** API:
    - **Python version**: Python 3.7.10
    - **Numpy version** 1.19.5

**Comment by senemaktas** [comment]
hi did you solve it? I have that error now? thanks.

**Comment by senemaktas** [comment]
Error:
Cuda check failed (209 vs. 0): no kernel image is available for execution on the device

Coming from:
- /.../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():115
- /..../openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
- /..../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():120
- /.../openpose/src/openpose/net/netCaffe.cpp:forwardPass():259
- /../openpose/src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():632
- ..../openpose/src/openpose/pose/poseExtractor.cpp:forwardPass():53
- /..../openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
- /....openpose/include/openpose/thread/worker.hpp:checkAndWork():93

Output turns None. How to solve it? @gineshidalgo99

**Comment by lastsongforu** [comment]
> Error:
> Cuda check failed (209 vs. 0): no kernel image is available for execution on the device
> 
> Coming from:
> 
> * /.../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():115
> * /..../openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
> * /..../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():120
> * /.../openpose/src/openpose/net/netCaffe.cpp:forwardPass():259
> * /../openpose/src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():632
> * ..../openpose/src/openpose/pose/poseExtractor.cpp:forwardPass():53
> * /..../openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
> * /....openpose/include/openpose/thread/worker.hpp:checkAndWork():93
> 
> Output turns None. How to solve it? @gineshidalgo99


Have you solved it? I meet the same problem

**Comment by senemaktas** [comment]
> > Error:
> > Cuda check failed (209 vs. 0): no kernel image is available for execution on the device
> > Coming from:
> > 
> > * /.../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():115
> > * /..../openpose/src/openpose/gpu/cuda.cpp:cudaCheck():37
> > * /..../openpose/src/openpose/net/netCaffe.cpp:reshapeNetCaffe():120
> > * /.../openpose/src/openpose/net/netCaffe.cpp:forwardPass():259
> > * /../openpose/src/openpose/pose/poseExtractorCaffe.cpp:forwardPass():632
> > * ..../openpose/src/openpose/pose/poseExtractor.cpp:forwardPass():53
> > * /..../openpose/include/openpose/pose/wPoseExtractor.hpp:work():107
> > * /....openpose/include/openpose/thread/worker.hpp:checkAndWork():93
> > 
> > Output turns None. How to solve it? @gineshidalgo99
> 
> Have you solved it? I meet the same problem

Unfortunelly,  still searching, https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1505#issuecomment-589534546 just saw today. maybe you can figure out. I do not understand

**Comment by hadi-ghnd** [comment]
@senemaktas have you found a solution for this?

**Comment by senemaktas** [comment]
> @senemaktas have you found a solution for this?

opss :( unfortunally, I am just running on Colab, and recently I get same error there...

**Comment by hadi-ghnd** [comment]
@senemaktas ok, thanks. I gave up, but I may try Colab as well.

**Comment by silverwzj** [comment]
I had fix this problem,
1.know your gpu's sm value(by deviceQuery),for example,my Tesla K80 is sm37
2.In cmake,set CUDA_ARCH to Manual
3.Open Advanced,find CUDA_NVCC_FLAGS,set value "-gencode arch=compute_37,code=sm_37"

**Comment by senemaktas** [comment]
> 
> 
> I had fix this problem, 1.know your gpu's sm value(by deviceQuery),for example,my Tesla K80 is sm37 2.In cmake,set CUDA_ARCH to Manual 3.Open Advanced,find CUDA_NVCC_FLAGS,set value "-gencode arch=compute_37,code=sm_37"

thank you very much, after clean installition i will try your solution

**Comment by mostafamdy** [comment]
> I had fix this problem, 1.know your gpu's sm value(by deviceQuery),for example,my Tesla K80 is sm37 2.In cmake,set CUDA_ARCH to Manual 3.Open Advanced,find CUDA_NVCC_FLAGS,set value "-gencode arch=compute_37,code=sm_37"

thanks, it works 
there is some additional information  
deviceQuery most properly located in "C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7\extras\demo_suite"
you will open cmd in this location and write  `deviceQuery.exe`
get CUDA Capability Major/Minor version number remove "." and use it as sm

https://stackoverflow.com/questions/62901027/cuda-error-209-cudalaunchkernel-returned-cudaerrornokernelimagefordevice
