### ISSUE TITLE
Can OpenPose support CUDA 11 version(RTX3090) 

### ISSUE THREAD

**Issue by Taylorminer** [CMU-Perceptual-Computing-Lab/openpose#2118]
Can OpenPose support CUDA 11 version(RTX3090) ? I try to deploy OpenPose on RTX 3090, and the terminal show this:
Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0) CUDNN_STATUS_NOT_INITIALIZED. It seems many people face the same problem.

**Comment by rlewkowicz** [comment]
@Taylorminer what os and what language are you trying to use? I can confirm it works on my 3090ti. I had to build from source on linux, and it was super painful. 

Regardless of OS, make sure cuda toolkit is installed. If you're using python install all your deps via anaconda as they usually have pre compiled binaries built in

**Comment by xiangyann** [comment]
@Taylorminer The problem with that is due to not enough mem for CUDNN. CUDNN works worse than without it in CUDA>=11
See https://github.com/CMU-Perceptual-Computing-Lab/openpose/issues/1864#issuecomment-774706976 for more details.
In short, compile OpenPose WITHOUT CUDNN and you'll be up and running in no time!

**Comment by mayank64ce** [comment]
@xiangyann how do I do that on google colab ?
