### ISSUE TITLE
cuDNN did not return a suitable algorithm for convolution.

### ISSUE THREAD

**Issue by FaterYU** [CMU-Perceptual-Computing-Lab/openpose#2166]
### Issue Summary

When I run ` ./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/`, it raises some error like `cuDNN did not return a suitable algorithm for convolution.`. But cudnn actually exists in system.

### Executed Command 

```shell
./build/examples/openpose/openpose.bin --video examples/media/video.avi --face --hand --write_json output_json_folder/ --logging_level 0 --disable_multi_thread
```

### Errors (if any)

```shell
Starting OpenPose demo...
Configuring OpenPose...
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducer():210
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToProducerType():170
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseMode():11
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToPoseModel():33
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToScaleMode():82
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToHeatMapScaleMode():116
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():147
/home/fate/openpose/openpose/src/openpose/utilities/flagsToOpenPose.cpp:flagsToDetector():147
Starting thread(s)...
Running configureThreadManager...
/home/fate/openpose/openpose/src/openpose/producer/producer.cpp:createProducer():417
renderModePose = 3
renderModeFace = 3
renderModeHand = 3
renderOutput = 1
renderOutputGpu = 1
renderFace = 1
renderHand = 1
renderHandGpu = 1
/home/fate/openpose/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():17
/home/fate/openpose/openpose/src/openpose/wrapper/wrapperAuxiliary.cpp:wrapperConfigureSanityChecks():192
userInputAndPreprocessingWsEmpty = 1
userOutputWsEmpty = 1
numberGpuThreads = -1
gpuNumberStart = 0
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
writeImagesCleaned =
writeKeypointCleaned =
writeJsonCleaned = output_json_folder/
writeHeatMapsCleaned =
modelFolder = models/
finalOutputSize = [1280,720]
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():370
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():435
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():440
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():451
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():456
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():505
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():510
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():557
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():562
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():601
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():606
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():645
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():662
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():679
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():698
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():714
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():747
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():772
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():777
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():781
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():797
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():798
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():807
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():824
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():844
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():865
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():874
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():878
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():884
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():943
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():959
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():965
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1041
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1075
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1179
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1203
/home/fate/openpose/openpose/include/openpose/wrapper/wrapperAuxiliary.hpp:configureThreadManager():1210
/home/fate/openpose/openpose/include/openpose/wrapper/wrapper.hpp:exec():419
/home/fate/openpose/openpose/include/openpose/thread/threadManager.hpp:exec():185
/home/fate/openpose/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/home/fate/openpose/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/home/fate/openpose/openpose/include/openpose/thread/queueBase.hpp:addPusher():362
/home/fate/openpose/openpose/include/openpose/thread/threadManager.hpp:exec():190
/home/fate/openpose/openpose/include/openpose/thread/thread.hpp:threadFunction():182
/home/fate/openpose/openpose/include/openpose/thread/thread.hpp:initializationOnThread():167
Starting initialization on thread. In /home/fate/openpose/openpose/src/openpose/pose/poseExtractorCaffe.cpp:netInitializationOnThread():172
E0213 23:19:58.991742  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:58.992041  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:58.994391  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:58.994503  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:58.997911  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:58.998121  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.006729  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.006994  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.010231  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.010463  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.016819  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.017113  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.023283  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.023458  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.026170  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.026306  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.040875  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.041147  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.054385  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.054597  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.084533  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.085356  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.097234  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.097445  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.104558  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.104784  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.126204  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.126806  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.137146  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.137329  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.168298  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.168570  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.177129  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.177700  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.184924  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.185128  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.208803  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.209472  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.217043  5952 cudnn_conv_layer.cpp:159] cuDNN did not return a suitable algorithm for convolution.
E0213 23:19:59.217331  5952 cudnn_conv_layer.cpp:184] cuDNN did not return a suitable algorithm for convolution.
F0213 23:19:59.228482  5952 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (1 vs. 0)  CUDNN_STATUS_NOT_INITIALIZED
*** Check failure stack trace: ***
    @     0x7f6175f151c3  google::LogMessage::Fail()
    @     0x7f6175f1a25b  google::LogMessage::SendToLog()
    @     0x7f6175f14ebf  google::LogMessage::Flush()
    @     0x7f6175f156ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f6175b3c115  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f6175c20e8d  caffe::Net<>::Init()
    @     0x7f6175c233a5  caffe::Net<>::Net()
    @     0x7f61767d829c  op::NetCaffe::initializationOnThread()
    @     0x7f61767f04e5  op::addCaffeNetOnThread()
    @     0x7f61767f16e4  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f61767f6025  op::PoseExtractorNet::initializationOnThread()
    @     0x7f61767eded7  op::PoseExtractor::initializationOnThread()
    @     0x7f61767e9727  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f617681be47  op::Worker<>::initializationOnThreadNoException()
    @     0x7f617681bf98  op::SubThread<>::initializationOnThread()
    @     0x7f617681d7c0  op::Thread<>::initializationOnThread()
    @     0x7f6176820d8c  op::Thread<>::threadFunction()
    @     0x7f61768211e5  op::Thread<>::exec()
    @     0x7f6176823ea4  op::ThreadManager<>::exec()
    @     0x7f6176879819  op::WrapperT<>::exec()
    @     0x5573bad3322c  openPoseDemo()
    @     0x5573bad2f6c7  main
    @     0x7f6176188083  __libc_start_main
    @     0x5573bad2f6fe  _start
[1]    5952 abort      ./build/examples/openpose/openpose.bin --video examples/media/video.avi --fac
```

### Type of Issue

- Execution error

### Your System Configuration
1. **Whole console output** https://pastebin.com/dPb5i8b7

3. **OpenPose version**: Latest GitHub code

4. **General configuration**:
    - **Installation mode**: CMake(Ubuntu)
    - **Operating system**  windows11+WSL2+Ubuntu20.04
    ```shell
    No LSB modules are available.
    Distributor ID: Ubuntu
    Description:    Ubuntu 20.04.5 LTS
    Release:        20.04
    Codename:       focal
    ```
    - **Operating system version** Ubuntu 20.04
    - **Release or Debug mode** release
    - Compiler 
    ```shell
    gcc (Ubuntu 9.4.0-1ubuntu1~20.04.1) 9.4.0
    Copyright (C) 2019 Free Software Foundation, Inc.
    This is free software; see the source for copying conditions.  There is NO
    warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
    ```

5. **Non-default settings**:
    - **3-D Reconstruction module added**? (by default: no):
    - Any other custom CMake configuration with respect to the default version? (by default: no):

6. **3rd-party software**:
    - **Caffe version**: Default from OpenPose, custom version, ...?
    - **CMake version** (`cmake --version` in Ubuntu):
    - **OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?

7. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
    ```shell
    {
       "cuda" : {
          "name" : "CUDA SDK",
          "version" : "11.7.1"
       },
       "cuda_cccl" : {
          "name" : "CUDA C++ Core Compute Libraries",
          "version" : "11.7.91"
       },
       "cuda_cudart" : {
          "name" : "CUDA Runtime (cudart)",
          "version" : "11.7.99"
       },
       "cuda_cuobjdump" : {
          "name" : "cuobjdump",
          "version" : "11.7.91"
       },
       "cuda_cupti" : {
          "name" : "CUPTI",
          "version" : "11.7.101"
       },
       "cuda_cuxxfilt" : {
          "name" : "CUDA cu++ filt",
          "version" : "11.7.91"
       },
       "cuda_demo_suite" : {
          "name" : "CUDA Demo Suite",
          "version" : "11.7.91"
       },
       "cuda_gdb" : {
          "name" : "CUDA GDB",
          "version" : "11.7.91"
       },
       "cuda_memcheck" : {
          "name" : "CUDA Memcheck",
          "version" : "11.7.91"
       },
       "cuda_nsight" : {
          "name" : "Nsight Eclipse Plugins",
          "version" : "11.7.91"
       },
       "cuda_nvcc" : {
          "name" : "CUDA NVCC",
          "version" : "11.7.99"
       },
       "cuda_nvdisasm" : {
          "name" : "CUDA nvdisasm",
          "version" : "11.7.91"
       },
       "cuda_nvml_dev" : {
          "name" : "CUDA NVML Headers",
          "version" : "11.7.91"
       },
       "cuda_nvprof" : {
          "name" : "CUDA nvprof",
          "version" : "11.7.101"
       },
       "cuda_nvprune" : {
          "name" : "CUDA nvprune",
          "version" : "11.7.91"
       },
       "cuda_nvrtc" : {
          "name" : "CUDA NVRTC",
          "version" : "11.7.99"
       },
       "cuda_nvtx" : {
          "name" : "CUDA NVTX",
          "version" : "11.7.91"
       },
       "cuda_nvvp" : {
          "name" : "CUDA NVVP",
          "version" : "11.7.101"
       },
       "cuda_sanitizer_api" : {
          "name" : "CUDA Compute Sanitizer API",
          "version" : "11.7.91"
       },
       "libcublas" : {
          "name" : "CUDA cuBLAS",
          "version" : "11.10.3.66"
       },
       "libcufft" : {
          "name" : "CUDA cuFFT",
          "version" : "10.7.2.91"
       },
       "libcufile" : {
          "name" : "GPUDirect Storage (cufile)",
          "version" : "1.3.1.18"
       },
       "libcurand" : {
          "name" : "CUDA cuRAND",
          "version" : "10.2.10.91"
       },
       "libcusolver" : {
          "name" : "CUDA cuSOLVER",
          "version" : "11.4.0.1"
       },
       "libcusparse" : {
          "name" : "CUDA cuSPARSE",
          "version" : "11.7.4.91"
       },
       "libnpp" : {
          "name" : "CUDA NPP",
          "version" : "11.7.4.75"
       },
       "libnvjpeg" : {
          "name" : "CUDA nvJPEG",
          "version" : "11.8.0.2"
       },
       "nsight_compute" : {
          "name" : "Nsight Compute",
          "version" : "2022.2.1.3"
       },
       "nsight_systems" : {
          "name" : "Nsight Systems",
          "version" : "2022.1.3.3"
       },
       "nvidia_fs" : {
          "name" : "NVIDIA file-system",
          "version" : "2.12.8"
       }
    }
    ```
    - **cuDNN version**:8.5.0.96
    - **GPU model** (`nvidia-smi` in Ubuntu):
    ```shell
    +-----------------------------------------------------------------------------+
    | NVIDIA-SMI 510.63       Driver Version: 512.36       CUDA Version: 11.6     |
    |-------------------------------+----------------------+----------------------+
    | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
    | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
    |                               |                      |               MIG M. |
    |===============================+======================+======================|
    |   0  NVIDIA GeForce ...  On   | 00000000:01:00.0 Off |                  N/A |
    | N/A   48C    P8    N/A /  N/A |    153MiB /  2048MiB |      4%      Default |
    |                               |                      |                  N/A |
    +-------------------------------+----------------------+----------------------+
    
    +-----------------------------------------------------------------------------+
    | Processes:                                                                  |
    |  GPU   GI   CI        PID   Type   Process name                  GPU Memory |
    |        ID   ID                                                   Usage      |
    |=============================================================================|
    |    0   N/A  N/A      3295      G   /Xwayland                       N/A      |
    +-----------------------------------------------------------------------------+
    ```

**Comment by jin03041209** [comment]
I have the same problem, did you solve it?

**Comment by FaterYU** [comment]
> I have the same problem, did you solve it?

Not yet. I am still trying to find a way.

**Comment by Azleur** [comment]
Same issue. Did you find a solution?

**Comment by saisritejakuppa** [comment]
Same issue. Did you find a solution?

**Comment by Tonoward** [comment]
Running into the same problem, I tried uninstalling everything (nvidia drivers/cuda/cudnn) and reinstalled again with the recomendations on the [prerequisites](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation/1_prerequisites.md) page (CUDA 11.7 and Cudnn 8.5.0 since I am in ubuntu 20.04) but still runinng on the same error. Can someone share some insights on this problem?

**Comment by FaterYU** [comment]
> 

It worked for me a little bit, but it also has some errors:
```shell
F0227 13:43:18.177312  7780 syncedmem.cpp:71] Check failed: error == cudaSuccess (2 vs. 0)  out of memory
*** Check failure stack trace: ***
    @     0x7fc1d4ce11c3  google::LogMessage::Fail()
    @     0x7fc1d4ce625b  google::LogMessage::SendToLog()
    @     0x7fc1d4ce0ebf  google::LogMessage::Flush()
    @     0x7fc1d4ce16ef  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fc1d4a3259a  caffe::SyncedMemory::mutable_gpu_data()
    @     0x7fc1d48cb336  caffe::Blob<>::mutable_gpu_data()
    @     0x7fc1d4908b60  caffe::BaseConvolutionLayer<>::forward_gpu_gemm()
    @     0x7fc1d4a6bac1  caffe::ConvolutionLayer<>::Forward_gpu()
    @     0x7fc1d49f22d2  caffe::Net<>::ForwardFromTo()
    @     0x7fc1d55a38f7  op::NetCaffe::forwardPass()
    @     0x7fc1d55878e7  op::detectHandKeypoints()
    @     0x7fc1d5588489  op::HandExtractorCaffe::forwardPass()
    @     0x7fc1d558355f  op::WHandExtractorNet<>::work()
    @     0x7fc1d55e80df  op::Worker<>::checkAndWork()
    @     0x7fc1d55e826b  op::SubThread<>::workTWorkers()
    @     0x7fc1d55f5ddd  op::SubThreadQueueInOut<>::work()
    @     0x7fc1d55ece41  op::Thread<>::threadFunction()
    @     0x7fc1d55ed1e5  op::Thread<>::exec()
    @     0x7fc1d55efea4  op::ThreadManager<>::exec()
    @     0x7fc1d5645819  op::WrapperT<>::exec()
    @     0x55c60140422c  openPoseDemo()
    @     0x55c6014006c7  main
    @     0x7fc1d4f54083  __libc_start_main
    @     0x55c6014006fe  _start
[1]    7780 abort      ./build/examples/openpose/openpose.bin --video examples/media/video.avi
```

Do you know if my memory of GPU is not enough? My GPU is MX450 with 2GB memory.

**Comment by Tonoward** [comment]
> > 
> Do you know if my memory of GPU is not enough? My GPU is MX450 with 2GB memory.

I think 2GB is not enough for AI processing. Even with my GPU (8GB), I sometimes have memory problems.

What I can suggest you is lowering the resolution of the image or video you want to process. Try with a really small image (something like 254x254) and see if that works for you. Then increase the resolution until you find a threshhold for your purpose. Also, try to close background processes as much as possible.

Other solutions would require you editing the source code, so if you just want to test this, lowering the resolution would be the fastest approach.
