### ISSUE TITLE
Unable to Run OpenPose in Colab (but always was able to before, did something change? )

### ISSUE THREAD

**Issue by pkudzia** [CMU-Perceptual-Computing-Lab/openpose#2182]
### Issue Summary
I have never had an issue before running OpenPose in Colab but now it suddenly does not work. I can't get any Colab book to work, even tried the example provided by Google. I tried different versions of OpenPose and various other approaches.

I always end up getting the following issue:

F0321 18:54:28.839044 14846 cudnn_conv_layer.cu:21] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0) CUDNN_STATUS_EXECUTION_FAILED *** Check failure stack trace: *** 

@ 0x7f0c084741c3 google::LogMessage::Fail() @ 0x7f0c0847925b google::LogMessage::SendToLog() @ 0x7f0c08473ebf google::LogMessage::Flush() @ 0x7f0c084746ef google::LogMessageFatal::~LogMessageFatal() @ 0x7f0c081eadaa caffe::CuDNNConvolutionLayer<>::Forward_gpu() @ 0x7f0c0816fba2 caffe::Net<>::ForwardFromTo() @ 0x7f0c08b292c6 op::NetCaffe::forwardPass() @ 0x7f0c08b46222 op::PoseExtractorCaffe::forwardPass() @ 0x7f0c08b412db op::PoseExtractor::forwardPass() @ 0x7f0c08b3edd0 op::WPoseExtractor<>::work() @ 0x7f0c08b6fb1f op::Worker<>::checkAndWork() @ 0x7f0c08b6fcab op::SubThread<>::workTWorkers() @ 0x7f0c08b7d7cd op::SubThreadQueueInOut<>::work() @ 0x7f0c08b74831 op::Thread<>::threadFunction() @ 0x7f0c087b2de4 (unknown) @ 0x7f0c084b4609 start_thread @ 0x7f0c085ee133 clone

The version of Open Pose s 1.7 and the CUDA detected: 11.8 (according to # !nvcc --version ) but when i run 
 !nvidia-smi the Tesla Titan T4 says it has CUDA 12. So perhaps this may be causing the issue ? 

Found cuDNN: ver. 8.7.0

### Executed Command (if any)
Note: add `--logging_level 0 --disable_multi_thread` to get higher debug information.

### OpenPose Output (if any)
F0321 18:54:28.839044 14846 cudnn_conv_layer.cu:21] Check failed: status == CUDNN_STATUS_SUCCESS (8 vs. 0) CUDNN_STATUS_EXECUTION_FAILED *** Check failure stack trace: *** 

### Type of Issue
Select the topic(s) on your post, delete the rest:
- Execution error

### Your System Configuration
1.  Running in COLAB 

3. **OpenPose version**: The version of Open Pose s 1.7 and the CUDA detected: 11.8
Found cuDNN: ver. 8.7.0

7. If **GPU mode** issue:
    - **CUDA version** (`cat /usr/local/cuda/version.txt` in most cases): 11.8
    - **cuDNN version**:8.70
    - **GPU model** (`nvidia-smi` in Ubuntu): Tesla Titan T4 (the GPU says it has Cuda 12 on it)

**Comment by ckot** [comment]
I've had issues with some other colab notebook breaking about 2 weeks ago where it worked one day and not the next.  It seemed that the base environment got upgraded.  in my case it was just some python packages which got more up-to-date versions which were incompatible with the code, and  I was able to prepend the notbook with a cell which did a pip remove and install older versions of those deps, but this sounds a little more complicated.

Is this a private notebook you put together yourself, or is it some commonly used colab notebook others use?

**Comment by mitesuti** [comment]
I am also having trouble with the exact same error.
I would like to know if you know how to solve this problem.

**Comment by ThomasWeikert** [comment]
Hey is there any solution to this? I am running into the same problem. @pkudzia did you try to run the OpenPose_JS.ipynb ?

**Comment by pkudzia** [comment]
Please don't quote me on this but apparently, it doesn't work with cudnn 8 yet. patch up solution that works is : 

  # Build OpenPose
  !cd openpose && rm -rf build || true && mkdir build && cd build && cmake .. -DUSE_CUDNN=OFF && make -j`nproc`
  
Let me know if that helps for now / if you find another method.

**Comment by ThomasWeikert** [comment]
Yes works for me! Thanks a lot!

**Comment by maryamho** [comment]
can we change the cudnn version?if so where and how we can do it for implementing openpose in colab?
