### ISSUE TITLE
Ubuntu 16 libcudnn.so.5 not found

### ISSUE THREAD

**Issue by arkceajin** [CMU-Perceptual-Computing-Lab/openpose#380]
After run `bash ./ubuntu/install_caffe_and_openpose_if_cuda8.sh` .
**Error:**

```
make: *** [.build_release/examples/tutorial_thread/3_user_input_processing_and_output.bin] error 1
/usr/bin/ld: warning: libcudnn.so.5, needed by 3rdparty/caffe/distribute/lib/libcaffe.so, not found (try using -rpath or -rpath-link)

```
 `libcudnn.so.5` can be found in /usr/local/cuda-8.0/lib64
```
ubuntu@scv:/usr/local/cuda-8.0/lib64$ ll libcudnn.so.5
lrwxrwxrwx 1 root root 17  1月 17 18:27 libcudnn.so.5 -> libcudnn.so.5.0.5*
```
Environment:

- Ubuntu 16
- CUDA 8
- cudnn 5

**Comment by gineshidalgo99** [comment]
You have different versions of CUDA, as OpenPose *.sh script looks in /usr/local/cuda by default.

Remove the build folders (in OpenPose and ./3rdparty/caffe) and use the CMake installer and specify your CUDA path.

**Comment by brinij** [comment]
In openpose/ubuntu/Makefile.config.Ubuntu16_cuda8.example (or the one that you use) add to LIBRARY_DIRS path to your folder (locate libcudnn.so), which is in my case /usr/local/cuda/lib64 , 
if that also fails, copy your library to /usr/local/lib

**Comment by arkceajin** [comment]
@brinij I tried to copy the whole cuDNN to `/usr/local/lib` which download from Nvidia, but still not worked. I fixed it by uninstall whole Nvidia driver and CUDA, make sure the system is clean, finally build succeeded.
