### ISSUE TITLE
Jetson TX2 run demo error:  Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED

### ISSUE THREAD

**Issue by Ramay7** [CMU-Perceptual-Computing-Lab/openpose#383]
### Executed Command (if any)
I have installed OpenPose on my Jetson TX2 through following the installation from [installation_jetson_tx2.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2.md), mainly by the cmmand:
`/ubuntu/install_caffe_and_openpose_JetsonTX2_JetPack3.1.sh`.

However, when I wanted to run on video by the command:
 `./build/examples/openpose/openpose.bin --video examples/media/video.avi`
 in [quick_start.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/quick_start.md), an unexpected error happened: 

### OpenPose Output (if any)
```
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)
F0118 19:33:27.378487 26261 cudnn_conv_layer.cpp:138] Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED
*** Check failure stack trace: ***
    @       0x7fa1883718  google::LogMessage::Fail()
    @       0x7fa1885614  google::LogMessage::SendToLog()
    @       0x7fa1883290  google::LogMessage::Flush()
    @       0x7fa1885eb4  google::LogMessageFatal::~LogMessageFatal()
    @       0x7fa1af6f28  caffe::CuDNNConvolutionLayer<>::Reshape()
    @       0x7fa1c25eb8  caffe::Net<>::Init()
    @       0x7fa1c280a4  caffe::Net<>::Net()
    @       0x7fa27d9af8  op::NetCaffe::initializationOnThread()
    @       0x7fa27f8868  op::addCaffeNetOnThread()
    @       0x7fa27f91f0  op::PoseExtractorCaffe::netInitializationOnThread()
    @       0x7fa27ee660  op::PoseExtractor::initializationOnThread()
    @       0x7fa281580c  op::SubThread<>::initializationOnThread()
    @       0x7fa2815de0  op::Thread<>::initializationOnThread()
    @       0x7fa281a890  op::Thread<>::threadFunction()
    @       0x7fa25b2280  (unknown)
    @       0x7fa100cfc4  start_thread
Aborted (core dumped)
```
the core problem is :  `Check failed: status == CUDNN_STATUS_SUCCESS (9 vs. 0)  CUDNN_STATUS_NOT_SUPPORTED`.

I don't know how to solve it, can you help me please?

### Type of Issue
- Execution error

### Your System Configuratio
**Operating system** (`lsb_release -a` in Ubuntu):
```
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial
```
**Installation mode**: CMake, sh script, manual Makefile installation, ... (Ubuntu); VS2015, VS2017, CMake, ... (Windows); ...?
install from [installation_jetson_tx2.md](https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation_jetson_tx2.md)
sh script
**CUDA version** (`cat /usr/local/cuda/version.txt` in most cases):
```
nvidia@tegra-ubuntu:~/NVIDIA_CUDA-8.0_Samples/1_Utilities/deviceQuery$ ./deviceQuery
./deviceQuery Starting...

 CUDA Device Query (Runtime API) version (CUDART static linking)

Detected 1 CUDA Capable device(s)

Device 0: "NVIDIA Tegra X2"
  CUDA Driver Version / Runtime Version          8.0 / 8.0
  CUDA Capability Major/Minor version number:    6.2
  Total amount of global memory:                 7851 MBytes (8232062976 bytes)
  ( 2) Multiprocessors, (128) CUDA Cores/MP:     256 CUDA Cores
  GPU Max Clock rate:                            1301 MHz (1.30 GHz)
  Memory Clock rate:                             1600 Mhz
  Memory Bus Width:                              128-bit
  L2 Cache Size:                                 524288 bytes
  Maximum Texture Dimension Size (x,y,z)         1D=(131072), 2D=(131072, 65536), 3D=(16384, 16384, 16384)
  Maximum Layered 1D Texture Size, (num) layers  1D=(32768), 2048 layers
  Maximum Layered 2D Texture Size, (num) layers  2D=(32768, 32768), 2048 layers
  Total amount of constant memory:               65536 bytes
  Total amount of shared memory per block:       49152 bytes
  Total number of registers available per block: 32768
  Warp size:                                     32
  Maximum number of threads per multiprocessor:  2048
  Maximum number of threads per block:           1024
  Max dimension size of a thread block (x,y,z): (1024, 1024, 64)
  Max dimension size of a grid size    (x,y,z): (2147483647, 65535, 65535)
  Maximum memory pitch:                          2147483647 bytes
  Texture alignment:                             512 bytes
  Concurrent copy and kernel execution:          Yes with 1 copy engine(s)
  Run time limit on kernels:                     No
  Integrated GPU sharing Host Memory:            Yes
  Support host page-locked memory mapping:       Yes
  Alignment requirement for Surfaces:            Yes
  Device has ECC support:                        Disabled
  Device supports Unified Addressing (UVA):      Yes
  Device PCI Domain ID / Bus ID / location ID:   0 / 0 / 0
  Compute Mode:
     < Default (multiple host threads can use ::cudaSetDevice() with device simultaneously) >

deviceQuery, CUDA Driver = CUDART, CUDA Driver Version = 8.0, CUDA Runtime Version = 8.0, NumDevs = 1, Device0 = NVIDIA Tegra X2
Result = PASS
```
```
nvidia@tegra-ubuntu:~/OpenPose/openpose$ cat /usr/local/cuda/version.txt
CUDA Version 8.0.84
```
**cuDNN version**:
```
nvidia@tegra-ubuntu:~/OpenPose/openpose$ cat /usr/local/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2
#define CUDNN_MAJOR      5
#define CUDNN_MINOR      1
#define CUDNN_PATCHLEVEL 10
--
#define CUDNN_VERSION    (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#include "driver_types.h"
```
**GPU model** (`nvidia-smi` in Ubuntu):
since Jetson TX2 is arrch64 (not x86_64) architecture, it seems that I cannot get GPU information by 'nvidia-smi'. So I take another way: `sudo nvpmodel -q verbose`
```
nvidia@tegra-ubuntu:~/OpenPose/openpose$ sudo nvpmodel -q verbose
[sudo] password for nvidia: 
NV Power Mode: MAXP_CORE_ARM
3
```
**Caffe version**: Default from OpenPose, custom version, ...?
Default from OpenPose

**OpenCV version**: pre-compiled `apt-get install libopencv-dev` (only Ubuntu); OpenPose default (only Windows); compiled from source? If so, 2.4.9, 2.4.12, 3.1, 3.2?; ...?
```
nvidia@tegra-ubuntu:~/OpenPose/openpose$ pkg-config --modversion opencv
2.4.13.1
```
Compiler (`gcc --version` in Ubuntu):
```
nvidia@tegra-ubuntu:~/OpenPose/openpose$ gcc --version
gcc (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
````

**Any information needed?**

**Comment by Ramay7** [comment]
Hi,
My colleague have helped me solve this problem by **reflushing OS**. Maybe some little unknown mistakes were made by me during the first time of OS flushing.

But also thanks a lot.

**Comment by elkalash** [comment]
@Ramay7 Hi,
I'm having actually an issue not so different than yours.
Starting pose estimation demo.
Auto-detecting all available GPUs... Detected 2 GPU(s), using 2 of them starting at GPU 0.
Starting thread(s)
F0129 13:19:41.124759 14582 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)  CUDNN_STATUS_INTERNAL_ERROR
*** Check failure stack trace: ***
    @     0x7f255c1d75cd  google::LogMessage::Fail()
    @     0x7f255c1d9433  google::LogMessage::SendToLog()
    @     0x7f255c1d715b  google::LogMessage::Flush()
    @     0x7f255c1d9e1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7f255c5d323b  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7f255c6c2b4c  caffe::Net<>::Init()
    @     0x7f255c6c5c20  caffe::Net<>::Net()
    @     0x7f255e1034e5  op::NetCaffe::initializationOnThread()
    @     0x7f255e2246c2  op::addCaffeNetOnThread()
    @     0x7f255e224fd6  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7f255e220d44  op::PoseExtractor::initializationOnThread()
    @     0x7f255e21e1de  op::WPoseExtractor<>::initializationOnThread()
    @     0x7f255e177ef6  op::SubThread<>::initializationOnThread()
    @     0x7f255e17a105  op::Thread<>::initializationOnThread()
    @     0x7f255e17a357  op::Thread<>::threadFunction()
    @     0x7f255e1946a5  std::_Mem_fn_base<>::operator()<>()
    @     0x7f255e194639  _ZNSt12_Bind_simpleIFSt7_Mem_fnIMN2op6ThreadISt10shared_ptrISt6vectorINS1_5DatumESaIS5_EEES3_INS1_6WorkerIS8_EEEEEFvvEEPSC_EE9_M_invokeIJLm0EEEEvSt12_Index_tupleIJXspT_EEE
    @     0x7f255e1943ea  std::_Bind_simple<>::operator()()
    @     0x7f255e1941ba  std::thread::_Impl<>::_M_run()
    @     0x7f255d836c80  (unknown)
    @     0x7f255cf886ba  start_thread
    @     0x7f255d2a541d  clone
    @              (nil)  (unknown)
Aborted (core dumped)
You said you solve it by reflushing OS,you've builded it on Ubuntu server？

**Comment by Ramay7** [comment]
@elkalash 
I use Openpose  on Nvidia Jetson TX2 and my system version is Ubuntu 16.04.
I have not met the problem you post above. But I hope [this link](https://github.com/tensorflow/tensorflow/issues/8879) will help you. 
Sorry:(

**Comment by elkalash** [comment]
it's ok...thank you @Ramay7 I've already solved it

**Comment by arynchoong** [comment]
Hi, I have the same issue. @elkalash  how did you solve it?

**Comment by elkalash** [comment]
@arynchoong Hi,
**Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0**
For me the solution was here,if the GPU is Used somewhere else you need to find out,and make it available to run your demo,in my case I builded it on an Ubuntu server and at the same time someone else was using the GPU ,so I got this error,and when the GPUs was free,I builded it again and It worked properly...

**Comment by Rafcin** [comment]
I set the Cuda make file to have the proper set on line 21 but I still get tossed the same error as above.
Any solutions?

**Comment by Ramay7** [comment]
Hi, @chigur 
I'm sorry that I have already resigned:(.   I remember that my ex-colleagues and I reflushed the OS by following some tutorials, such as [this](https://blog.csdn.net/qq_17278169/article/details/79074010) (in Chinese). I think you can also get some alike net resources. Good luck to u ~

**Comment by chigur** [comment]
@Ramay7 Thanks for the link, but, luckily, I got it working. All I had to do was build the caffe independently.

**Comment by Rafcin** [comment]
Did it work with Cuda 9?

**Comment by chigur** [comment]
Actually, my own machine has CUDA 9 and cuDNN 7.5. I was able to successfully build and run the v1.3.0 of openpose on it.

**Comment by Rafcin** [comment]
And this is in a Jetson Tx2 right? I'm curious, did you just compile
normally?

**Comment by Rafcin** [comment]
Because I get thrown errors that caffeine or openpose won't accept Cuda 9

**Comment by chigur** [comment]
I am sorry but no. I am running Nvidia 1080 on my machine and Titan X on the servers.
