### ISSUE TITLE
CUDNN_STATUS_ARCH_MISMATCH

### ISSUE THREAD

**Issue by jasminehtwe** [CMU-Perceptual-Computing-Lab/openpose#681]
I installed Openpose under the installation instruction. Completed 'make all' successfully.
but, when I run ./build/examples/openpose/openpose.bin --video examples/media/video.avi
I got the following errror. Please help me how can I solve this error?

GPU:  GeForce GTX 550 Ti
CUDA: 8.0
CuDNN: 5.1
OS: Ubuntu

Starting OpenPose demo...
Auto-detecting all available GPUs... Detected 1 GPU(s), using 1 of them starting at GPU 0.
Starting thread(s)...
F0628 13:44:06.798274 24168 cudnn_conv_layer.cpp:53] Check failed: status == CUDNN_STATUS_SUCCESS (6 vs. 0)  CUDNN_STATUS_ARCH_MISMATCH
*** Check failure stack trace: ***
    @     0x7fd5bddeb5cd  google::LogMessage::Fail()
    @     0x7fd5bdded433  google::LogMessage::SendToLog()
    @     0x7fd5bddeb15b  google::LogMessage::Flush()
    @     0x7fd5bddede1e  google::LogMessageFatal::~LogMessageFatal()
    @     0x7fd5be46dbc3  caffe::CuDNNConvolutionLayer<>::LayerSetUp()
    @     0x7fd5be5a3453  caffe::Net<>::Init()
    @     0x7fd5be5a6290  caffe::Net<>::Net()
    @     0x7fd5bfbaf2f8  op::NetCaffe::initializationOnThread()
    @     0x7fd5bfca2ddb  op::addCaffeNetOnThread()
    @     0x7fd5bfca389c  op::PoseExtractorCaffe::netInitializationOnThread()
    @     0x7fd5bfcbc5b0  op::PoseExtractorNet::initializationOnThread()
    @     0x7fd5bfca7771  op::PoseExtractor::initializationOnThread()
    @     0x7fd5bfcafce1  op::WPoseExtractor<>::initializationOnThread()
    @     0x7fd5bfc7cc61  op::SubThread<>::initializationOnThread()
    @     0x7fd5bfc7d250  op::Thread<>::initializationOnThread()
    @     0x7fd5bfc8219d  op::Thread<>::threadFunction()
    @     0x7fd5bf5dbc80  (unknown)
    @     0x7fd5bc6666ba  start_thread
    @     0x7fd5bf04a41d  clone
    @              (nil)  (unknown)
Aborted (core dumped)

**Comment by JasOlean** [comment]
I solved this one. For cuda 8.0, CuDNN's compute capability needs at least 3.0. So, I change my GPU card (GTX 1070 Ti with CC 3.0).
