### ISSUE TITLE
Runtime error when processing image directory

### ISSUE THREAD

**Issue by andieheung-s4d** [CMU-Perceptual-Computing-Lab/openpose#724]
My environment:
OS: Ubuntu 16.04
GPU: Nvidia Tesla M60
CUDA 8
Cudnn 5.1
OpenCV latest
CAFFE

I built Openpose in Ubuntu 16.04 on AWS g3.4xlarge instance and tried to test it by this command:
./build/examples/openpose/openpose.bin --image_dir /data/openpose/build/examples/files/ --face --hand

Then it gave me this...
(OpenPose 1.3.0:41242): Gtk-WARNING **: cannot open display: 
E0712 07:32:30.913461 41257 common.cpp:114] Cannot create Cublas handle. Cublas won't be available.
E0712 07:32:30.913921 41257 common.cpp:121] Cannot create Curand generator. Curand won't be available.
F0712 07:32:30.914083 41257 common.cpp:152] Check failed: error == cudaSuccess (35 vs. 0)  CUDA driver version is insufficient for CUDA runtime version
*** Check failure stack trace: ***
*** Error in `./build/examples/openpose/openpose.bin': corrupted size vs. prev_size: 0x0000000000f775f0 ***
    @     0x7effca5295cd  google::LogMessage::Fail()
    @     0x7effca52b433  google::LogMessage::SendToLog()

How can I fix it?
Is the .bin corrupted as the error message said? Do I need to reinstall it again?

Btw, this error has gone when I didn't run it with --face --hand option.
So how can I get the face and hand options work?
Thanks!

**Comment by gineshidalgo99** [comment]
That's a CUDA error. Posting rules:
```
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
```
