### ISSUE TITLE
Get keypose + 8 vs. 0 invalid device function, Windows

### ISSUE THREAD

**Issue by paloskar** [CMU-Perceptual-Computing-Lab/openpose#73]
Hello,

First of all, thank you for letting people use your project, it is very impressive!

Second: I'm developing under Windows, thus have a hard time to make openpose compile. Actually, I compiled the library itself, but I'm struggling with making the examples work, due to missing (or wrong types of) third party lib files, which your project relies on. The only thing that really works on my setup is the demo executable which you have included. But I can't seem to get any information out of the demo. Would it be possible to have a demo which would read a webcam source (which it already does) and somehow numerically output the recognized body poses?

Any feedback on this would be greatly appreciated.

Keep up the great work,

Oskar

**Comment by gineshidalgo99** [comment]
Compiling OpenPose: Did you follow the exact (and most updated) Windows instructions?
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#windows

What lib files are missing? No file should be missing.

If the demo is running you can do what you are looking for. Check the documentation.

**Comment by paloskar** [comment]
Hi gineshidalgo99,

Let me answer your last comment first: I did look into the documentation of the demo and could not find what I was looking for. Specifically I would need the detected kinematic chains' coordinates (either 3D or 2D) to be output. Could you tell me if this is available?

Concerning the installation procedure:

I tried following the instructions you provided, but step 3.iii of the library installation fails for me when I execute scripts\build_win.cmd. Specifically cmake reports this:

**-- The C compiler identification is unknown
-- The CXX compiler identification is unknown**

The compiler is selected as: 

**INFO: CMAKE_GENERATOR            = "Visual Studio 14 2015 Win64"**

And I do have it installed on my system. When I run cmake --help it gives me this:

**The following generators are available on this platform:
  Visual Studio 15 2017 [arch] = Generates Visual Studio 2017 project files.
                                 Optional [arch] can be "Win64" or "ARM".
  Visual Studio 14 2015 [arch] = Generates Visual Studio 2015 project files.
                                 Optional [arch] can be "Win64" or "ARM".**

So I have VS2015 installed but cmake cannot find it. I understand that you cannot provide support for cmake issues, but my point is that there are too many steps in your installation instructions in which many things could go wrong. You have to have "all stars aligned" or be an expert of each involved tool and library to make this compile. Could there be any easier solution? The OpenCV approach comes to mind where they provide both .lib and .dll files with the necessary headers which allows me to just use the library without the need of compiling it. 

All in all, please don't take this as negative criticism, I'm just trying to help myself and others be able to use your algorithms. It's already great that you guys put out your code and allowed for people to access it, thank you for that.

Cheers,

Oskar

**Comment by gineshidalgo99** [comment]
Hi Oskar,

I am sorry for my silence, I was working in a new Windows version. Please, feel free to try the new Windows version. It should be much easier to install. Let me know if you face any problems.

kinematic chains' coordinates (either 3D or 2D) to be output: 2D is possible. Please check https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/output.md
It has the 2D data format. In addition, I added today to that document how to get it from the Datum object (in case you use tutorial_wrapper files). Again, let me know any question about.

**Comment by paloskar** [comment]
Hi Gines,

Thanks for the update and for the new Windows version! Now finally I'm able to compile and link OpenPose and all exaples/demo, but unfortunately they break after I start them. The error stems from line 86 in netCaffe.cpp:

**F0711 13:17:47.862519 12800 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: *****

Any idea what might be wrong? I do have a Cuda graphics card (GTX 1060) and the latest Cuda Toolkit installed (8.0). I know Cuda works, because I'm able to run the OpenPoseDemo.exe you provided, but cannot run the one I compiled. 

Any help would be greatly appreciated!

Keep up the great work,

Oskar

**Comment by gineshidalgo99** [comment]
Caffe with CUDA support is being a real pain to make it PC independent... I am releasing later today a new portable version. I'll keep you posted so you can try it then. Sorry for all the troubles, but right now it is working on my 3 Windows devices, so I cannot really test it too much more.
The problem you are facing is the CUDA version of Caffe, but it should work on your device since I am testing also a 10XX Nvidia series model... Let me release this new update and we can continue from there. Thanks!

**Comment by gineshidalgo99** [comment]
@paloskar Hi, I've just released a version that does not need Caffe installation.

In addition, if you do not care about the library itself, and you only plan to use the demo, I added a portable demo that does not need any kind of installation at all (nor CUDA nor Visual Studio installation).

Please let me know if you can run them successfully. Thanks!

**Comment by paloskar** [comment]
Hi Gines,

The new version works great! Finally, I was able to compile and run it under Windows. Perfect! Thanks for your effort to make this available for us.

A quick question: your system outputs 2D coordinates in the image frame and not 3D coordinates in the world frame, right? I.e. it does not estimate body pose in 3D space?

Thanks again!

Oskar

**Comment by gineshidalgo99** [comment]
OK great!

No, only 2D, unless you have a stereo camera system and do 3-D reprojection, something like this:
https://github.com/CMU-Perceptual-Computing-Lab/openpose/blob/master/doc/installation.md#openpose-3d-demo
