### ISSUE TITLE
ERROR: Check failed: error == cudaSuccess (8 vs. 0)  invalid device function *** Check failure stack trace: ***

### ISSUE THREAD

**Issue by ekim1423** [CMU-Perceptual-Computing-Lab/openpose#798]
Hello, I'm trying to run OpenPoseDemo.exe from window 10 with Cuda 8.0 using Titan V. I'm keep getting "Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***" error and I cannot figure out what causes this error and what the solution is. I did not download Caffe separately (just using the downloaded caffe that was provided from the instruction).

### Executed Command (if any)
 bin\OpenPoseDemo.exe --num_gpu=1 --video=examples\media\video.avi

### OpenPose Output (if any)
Starting OpenPose demo...
Starting thread(s)...
F0827 17:36:07.365116  4040 pooling_layer.cu:212] Check failed: error == cudaSuccess (8 vs. 0)  invalid device function
*** Check failure stack trace: ***

### Type of Issue
- Execution error
- Help wanted
- Question

### Your System Configuration
1. **OpenPose version**: f49e184

2. **General configuration**:
    - **Installation mode**: CMake
    - **Operating system** : Window 10
    - **Release or Debug mode**: Release
    - **Compiler**: Visual Studio 2015 - Visual C++ 14.0

3. **Non-default settings**:
    - **3-D Reconstruction module added**? NO
    - Any other custom CMake configuration with respect to the default version?  NO

4. **3rd-party software**:
    - **Caffe version**: Default from OpenPose
    - **CMake version** : 3.12.1
    - **OpenCV version**:  OpenPose default

5. If **GPU mode** issue:
    - **CUDA version**:  8.0.61
    - **cuDNN version**: 6.0.21
    - **GPU model** : NVIDIA TITAN V and NVIDIA QUADRO P600

8. If **Windows** system:
    - Portable demo or compiled library? Demo

**Comment by shrubb** [comment]
What happens if you restrict execution to one GPU?

```bash
CUDA_VISIBLE_DEVICES=0 bin\OpenPoseDemo.exe --num_gpu=1 --video=examples\media\video.avi
CUDA_VISIBLE_DEVICES=1 bin\OpenPoseDemo.exe --num_gpu=1 --video=examples\media\video.avi
```

**Comment by ekim1423** [comment]
I fixed it by adding 'CUDA_FORCE_PTX_JIT=1' on the environmental variables.

However, I'm facing the different problem. I don't get the same error but the popped-up window just get stuck on black screen saying "not responding".

I'm able to get the images from webcam without any openpose computation; but when runnign the demo, the screen gets freeze.

Please help me!

**Comment by gineshidalgo99** [comment]
### Posting rules
1. **Fill** the **Your System Configuration section (all of it!)** if you have some kind of error or performance question.
3. **No** questions about **3rd party libraries**.
    - Caffe errors/issues, check [Caffe](http://caffe.berkeleyvision.org) documentation.
    - CUDA check failed errors: They are usually fixed by re-installing CUDA, then re-installing the proper cuDNN version, and then re-compiling (or re-installing) OpenPose. Otherwise, check for help in CUDA forums.
    - OpenCV errors: Install the default/pre-compiled OpenCV or check for online help.

**Comment by ekim1423** [comment]
By the way @shrubb , the execution line does not work. Throws me this errror:
CUDA_VISIBLE_DEVICES=1 : The term 'CUDA_VISIBLE_DEVICES=1' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At line:1 char:1
+ CUDA_VISIBLE_DEVICES=1 bin\OpenPoseDemo.exe --num_gpu=1 --video=examp ...
+ ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (CUDA_VISIBLE_DEVICES=1:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by shrubb** [comment]
Environment variables should be set differently in Windows, see this: https://devtalk.nvidia.com/default/topic/543698/cuda-setup-and-installation/use-only-one-of-two-gpu-cards-on-a-pc/

**Comment by kjh71494** [comment]
@EunSolKim-Nano hello so have you solved this issue? I am having the same issue with my 1660ti..

**Comment by gineshidalgo99** [comment]
Download the latest OP if you are using the 1660 Ti. And be sure to fully follow the install instructions

**Comment by kjh71494** [comment]
I will give it a try! thanks for the quick reply!

2019년 3월 16일 (토) 오전 3:53, Gines <notifications@github.com>님이 작성:
